# Generated by Django 4.0.4 on 2022-05-04 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('recipe_url', models.CharField(max_length=500)),
                ('image_url', models.CharField(max_length=500)),
                ('ingredient', models.CharField(max_length=500)),
                ('calories', models.CharField(max_length=50)),
                ('total_time', models.CharField(max_length=10)),
                ('cuisine', models.CharField(max_length=100)),
                ('mealType', models.CharField(max_length=100)),
                ('dishType', models.CharField(max_length=100)),
            ],
        ),
    ]
